version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    environment:
      NODE_PENDING_DEPRECATION:1
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run:
                name: Run Tests
                command: npm test
                environment:
                  NODE_PENDING_DEPRECATION: 1
                  NODE_OPTIONS: '--throw-deprecation'
workflows:
    build-and-test:
      jobs:
        - build-and-test
